### ISSUE TITLE
REQ: Key Press during boot-up

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#24] opened 2017-09-18 13:13 UTC
Would it be possible to add the possibility to virtually push a certain key during boot, specifically the CTRL so you can boot with 1 drive, clearing up some extra memory.

**Comment by oh-ren** [comment] 2017-09-18 14:29
Duplicate of #14?

**Comment by ppeccin** [comment] 2017-09-18 14:30
Yes, I'll think of something for the next release.
Thanks

**Closed** 2017-09-18 14:31 UTC

**Comment by oh-ren** [comment] 2017-09-20 10:49
Might be a good thing to determine which keys or key-combos should be supported.

In any case:
* <kbd>CTRL</kbd> - do not initialize 2nd floppy drive. Frees RAM, required for some (disk) software;
* <kbd>SHIFT</kbd> - do not initialize any floppy drive, frees more RAM. Required from some cassette software I believe.

There are some other keys for certain BIOSes. Likek e.g. the NMS-1205 (Music Module) which requires <kbd>ESC</kbd> to be pressed to prevent internal software from booting.

Some software have a keep <kbd>SELECT</kbd> pressed for 60Hz are something like that right>
But that's **after** boot of course, and often **after** some screen or something.

Any other keys, or combo's perhaps?

**Comment by TFHFony** [comment] 2017-09-20 13:03
I think your list is pretty complete. Although there are some machines with
built in software (like wordsprocessors, Arabic stuff, etc...). I don't
know what keys those require.
