### ISSUE TITLE
DSK limited to 80 sectors

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#101] opened 2023-12-18 13:00 UTC
.DSK emulation is limited to 720Kbyte / 80 sectors. Non-Standard disks that use the 81st or 82nd sector cannot be loaded as a disk image.
Example: https://download.file-hunter.com/Games/MSX2/DSK/Dummieland%20(1994)(Soksoft)(Disk%201%20of%202).zip

The use of extra sectors is quite common, also as  a copy-protection.
I've also requested the support of .DMK images (https://github.com/ppeccin/WebMSX/issues/66) which could help running this kind of disks.

**Comment by NullPointerReference** [comment] 2024-03-08 22:11
This is possibly a quick-win; by changing:

https://github.com/ppeccin/WebMSX/blob/122834bb693556fe6cf70a468ecd2f68c5d99950/src/main/room/disk/DiskImages.js#L546

to: `this.MEDIA_TYPE_VALID_SIZES=[755712,746496,737280,655360,377856,373248,368640,327680,184320,163840]`

I.e. adding the length for double-sided, 82, 81 tracks and single-sided 82 and 81 disk-image sizes (in that) order.
This seems to work with the provided example file

**Comment by NullPointerReference** [comment] 2024-04-22 14:39
PS: Also tested this on file-hunter.com (thanks @TFHFony) and it seems to work as intended with the given example(s). Note that the proposed 'quick-win' only supports this for Double-density single- AND double-sided images; and did not extend the format to the 184320 and 163840 sizes/formats as I'm unfamiliar with these ...

**Comment by ppeccin** [comment] 2024-12-14 00:00
Fixed in 6.0.6

**Closed by ppeccin** 2024-12-14 00:00 UTC
