### ISSUE TITLE
Why is CHANNEL_VOLUME_CURVE_POWER = 30?

### ISSUE THREAD

**Issue by leo-hydraulic** [ppeccin/WebMSX#102] opened 2023-12-31 14:39 UTC
This is more just a question than a bug, but there was no "Discussion" section in the project. Maybe add comments as a fix?

I was wondering where did the value of 30 come from in modeling the volume curve for the PSG:
https://github.com/ppeccin/WebMSX/blob/master/src/main/msx/audio/PSGAudio.js#L292

I notice it's a simple exponential formula, was just wondering why choose 30 as the base. I tried tracking previous commits, and the value used to be 16, and changed to 30 without comments. I wonder, is this just an aesthetic change because it "sounds good", or is that taken from a datasheet, or oscilloscope measurements, etc?

I've been doing a few experiments with MSX audio myself, and I've been taking WebMSX as a source of information and inspiration. Great project, and thanks!

**Comment by inchl** [comment] 2024-01-22 16:10
It is a bug!

Webmsx plays terribly psg samples, until now I though it was caused by the fact that it's a javascript-based emulator. However its because of a incorrect volume-table being used.

function createVolumeCurve() {
    for (var v = 0; v < 16; v++)
        volumeCurve[v] = (Math.pow(CHANNEL_VOLUME_CURVE_POWER, v / 15) - 1) / (CHANNEL_VOLUME_CURVE_POWER - 1) * CHANNEL_MAX_VOLUME;
}

When the code is changed into (below).... the psg samples are being played correctly!

function createVolumeCurve() {
    for (var v = 1; v < 16; v++)
        volumeCurve[v] = Math.pow(2, -(15-v)/2) * CHANNEL_MAX_VOLUME;
}

more info:
[https://map.grauw.nl/articles/psg_sample.php](https://map.grauw.nl/articles/psg_sample.php)

https://github.com/ppeccin/WebMSX/assets/19953254/95d99242-d132-465b-bd0a-8f58e4ecd897

**Comment by ppeccin** [comment] 2024-01-23 20:23
Hi!

Hum... That's interesting... I will do some testing and fix that for the
next release!
Thanks for the report and the solution!  :-)

Can you point me to the games or software you were using when you detected
the problem?

Paulo

**Comment by inchl** [comment] 2024-01-24 18:23
Here are three of our projects playing samples/music via psg:

[https://nopmsx.nl/wp-content/uploads/2024/01/BBCNewYearsEve2023ASCII16.zip](https://nopmsx.nl/wp-content/uploads/2024/01/BBCNewYearsEve2023ASCII16.zip)
[https://nopmsx.nl/wp-content/uploads/2023/10/KingsValleyEnhanced9811ASCII16.zip](https://nopmsx.nl/wp-content/uploads/2023/10/KingsValleyEnhanced9811ASCII16.zip)
[https://nopmsx.nl/wp-content/uploads/2023/10/KingsValleyEnhancedFeaturingBartRoijmans9821ASCII16.zip](https://nopmsx.nl/wp-content/uploads/2023/10/KingsValleyEnhancedFeaturingBartRoijmans9821ASCII16.zip)

Info about the logarithmic volume scale can be found at grauws website:
[https://map.grauw.nl/articles/psg_sample.php](https://map.grauw.nl/articles/psg_sample.php)

Stephan

**Comment by NullPointerReference** [comment] 2024-03-13 11:19
Hi Stephan, 

I applied your changes to the createVolumeCurve() and tried https://nopmsx.nl/wp-content/uploads/2023/10/KingsValleyEnhanced9811ASCII16.zip, but that doesn't seem to sound fully correct still (compared to OpenMSX) ? 

Am I doing something wrong perhaps or is there still some difference in emulation that possibly needs to be addressed ?

**Comment by inchl** [comment] 2024-03-13 13:34
Might be this:
In javascript arrays are not initliazed... So manually setting volumeCurve[0] = 0 is required (for loops starts at 1). Index 0 cannot be calculated with the formula. Must be 0!

**Comment by NullPointerReference** [comment] 2024-03-13 13:38
I tested with index 0 explicitly set to 0 too, as I noticed it to ('empty'); it didn't help (much) :)

**Comment by inchl** [comment] 2024-03-13 13:41
Haha... Try changing the closure variables during playback / during a running webmsx.... Setting all 16 as they should be... Then it works!

**Comment by NullPointerReference** [comment] 2024-04-22 14:30
@ppeccin: @inchl, @TFHFony and I tested the (by @inchl) proposed curve - with the additional 'volumeCurve[0] = 0' - extensively and put it on file-hunter.com for testing for about a month.  We think it solves this audio-emulation issue and has no further negative impact. The complete snipplet is as follows, no additional changes outside mentioned code required.

`function createVolumeCurve() {
    volumeCurve[0] = 0;
    for (let v = 1; v < 16; v++) volumeCurve[v] = Math.pow(2, -(15-v)/2) * CHANNEL_MAX_VOLUME;
}`

**Comment by inchl** [comment] 2024-11-11 13:25
Hey Paulo,

Would be great if you could implement the suggested bugfix for playing PSG-samples. This weekend our project 'Goonies enhanced' will be released, but sadly your emulator does not play the samples correctly due to incorrect volume formula used.... 

fix:
`
function createVolumeCurve() { volumeCurve[0] = 0; for (let v = 1; v < 16; v++) volumeCurve[v] = Math.pow(2, -(15-v)/2) * CHANNEL_MAX_VOLUME; }
`

The available fix is tested and is online at file-hunter since april this year. Hopefully you can implement this fix also at webmsx.org.

Thanks

Stephan (NOP)

**Closed** 2024-12-12 23:43 UTC

**Comment by ppeccin** [comment] 2024-12-13 01:07
Fixed on 6.0.5
